// This file is generated automatically during PYLON build process
// DO NOT EDIT

#define PYLON_VERSION_MAJOR          5
#define PYLON_VERSION_MINOR          0
#define PYLON_VERSION_SUBMINOR       0
#define PYLON_VERSION_BUILD          6150
#define PYLON_VERSIONSTRING_MAJOR    "5"
#define PYLON_VERSIONSTRING_MINOR    "0"
#define PYLON_VERSIONSTRING_SUBMINOR "0"
#define PYLON_VERSIONSTRING_BUILD    "6150"
#define PYLON_VERSIONSTRING_SUFFIX   "VC120"

#define PYLON_VERSIONSTRING_COMMENT  "10/30/2015 12:40PM; GVMB0010"
